# A type describing a single blocked section between 2 locations
type BlockedSection {
  _id: ID
  # the reson for blocking this section
  reason: String
  # the from point
  from: String
  # the to point
  to: String
}

input InputBlockedSection {
  reason: String!
  from: String!
  to: String!
}
