# A type describing a single class
type Class {
  _id: ID!
  name: String!
  level: String!
  number: Int!
  schedule: [TimeSlot]
  students: [Student]!
}

input InputClass {
    name: String!
    level: String!
    number: Int!
    # list of new timeslots on schedule
    schedule: [InputTimeSlot]
}