# A type describing a single class
type Class {
  _id: ID!
  name: String!
  educationStage: EducationStage!
  schedule: [TimeSlot]!
  students: [Student]!
}

input InputClass {
    name: String!
    level: String!
    number: Int!
    # list of new timeslots on schedule
    schedule: [InputTimeSlot]
}

enum EducationStage{
  ELEMENTRY
  JUNIOR_HIGH
}