# A type describing a single class
type Class {
  _id: ID!
  name: String!
  grade: String!
  schedule: [TimeSlot]!
  students: [Student]!
}

input InputClass {
    name: String!
    level: String!
    # grade of class /[a-z]/
    grade: String!
    # list of new timeslots on schedule
    schedule: [InputTimeSlot]
}

