# A type describing a single lesson on a timetable.
type Lesson {
  # The lesson's start time on the 24-hour clock.
  startTime: String!
  # The lesson's end time on the 24-hour clock.
  endTime: String!
  # The lesson's name.
  title: String!
  # The room(s) in which the lesson is held.
  rooms: [Room!]!
}