# A type that describes a room.
type Location {
  # The location number
  _id: ID!
  # The location name
  name: String
  # location name from the 3D map model
  location_id: String
  # The lat lan cordinates
  position: Point
  icon: String
  type: String
  image_id: String
}

input InputLocation {
  # optional id for when updating schedules
  _id: ID
  name: String
  location_id: String
  position: InputPoint
  icon: String
  type: String
  image_id: String
}
