# A type that describes a room.
type Room {
  # The room number
  _id: ID!
  # The room name
  name: String
  # flag indicating if room is disabled
  disabled: Boolean!
  # The lat lan cordinates
  position: Point
}