type Query{
    getStudents: [Student]
    getStudent(id: ID!): Student
    
    getUsers:  [User]
    getUser(id: ID!): User

    classes: [Class]!
    classById(id: ID!): Class
    classByName(name: String): Class
}