type Query{
    people: [Person]
    person(id: ID!): Person
    
    users:  [User]
    user(id: ID!): User

    classes: [Class]!
    classById(id: ID!): Class
    classByName(name: String): Class

    lessons: [Lesson]!
}