# A type describing reminder time in student schedule
type ReminderTime {
  # numeric chars (0, 1,...6) represents the dayIndex of remindertime
  daysindex: [Int!]
  hours: [String!]
}

input InputReminderTime {
  daysindex: [Int!]
  hours: [String!]
}
