type Schedule {
    sun_0: Lesson
    sun_1: Lesson
    sun_2: Lesson
    sun_3: Lesson
    sun_4: Lesson
    sun_5: Lesson
    sun_6: Lesson
    sun_7: Lesson
    sun_8: Lesson
    sun_9: Lesson
    sun_10: Lesson
    sun_11: Lesson
    sun_12: Lesson
    sun_13: Lesson
    sun_14: Lesson
    mon_0: Lesson
    mon_1: Lesson
    mon_2: Lesson
    mon_3: Lesson
    mon_4: Lesson
    mon_5: Lesson
    mon_6: Lesson
    mon_7: Lesson
    mon_8: Lesson
    mon_9: Lesson
    mon_10: Lesson
    mon_11: Lesson
    mon_12: Lesson
    mon_13: Lesson
    mon_14: Lesson
    tue_0: Lesson
    tue_1: Lesson
    tue_2: Lesson
    tue_3: Lesson
    tue_4: Lesson
    tue_5: Lesson
    tue_6: Lesson
    tue_7: Lesson
    tue_8: Lesson
    tue_9: Lesson
    tue_10: Lesson
    tue_11: Lesson
    tue_12: Lesson
    tue_13: Lesson
    tue_14: Lesson
    wed_0: Lesson
    wed_1: Lesson
    wed_2: Lesson
    wed_3: Lesson
    wed_4: Lesson
    wed_5: Lesson
    wed_6: Lesson
    wed_7: Lesson
    wed_8: Lesson
    wed_9: Lesson
    wed_10: Lesson
    wed_11: Lesson
    wed_12: Lesson
    wed_13: Lesson
    wed_14: Lesson
    thu_0: Lesson
    thu_1: Lesson
    thu_2: Lesson
    thu_3: Lesson
    thu_4: Lesson
    thu_5: Lesson
    thu_6: Lesson
    thu_7: Lesson
    thu_8: Lesson
    thu_9: Lesson
    thu_10: Lesson
    thu_11: Lesson
    thu_12: Lesson
    thu_13: Lesson
    thu_14: Lesson
    fri_0: Lesson
    fri_1: Lesson
    fri_2: Lesson
    fri_3: Lesson
    fri_4: Lesson
    fri_5: Lesson
    fri_6: Lesson
    fri_7: Lesson
    fri_8: Lesson
    fri_9: Lesson
    fri_10: Lesson
    fri_11: Lesson
    fri_12: Lesson
    fri_13: Lesson
    fri_14: Lesson
}