# add full schedule class + student
type Student {
  _id: ID!
  username: String!
  password: String!
  email: String
  firstname: String
  lastname: String
  gender: Gender
  class: Class
  schedule: [TimeSlot!]
  # teacher: Teacher!
}

input InputStudent {
    username: String
    password: String
    email: String
    firstname: String
    lastname: String
    gender: Gender
    class_id: String
    schedule: [InputTimeSlot!]
}