# A type describing a single time slot on the class/student schedule
type TimeSlot {
  # 2 numeric chars (0_0, 0_1...) represents the dayIndex_hourIndex of timeslot grid cell
  index: String!
  hours: String
  original: Original
  lesson: Lesson
  location: Location
  customized: Boolean
}

input InputTimeSlot {
  index: String!
  hours: String
  original: InputOriginal
  lesson: InputLesson!
  location: InputLocation
  customized: Boolean
}
