type User {
  _id: ID!
  username: String!
  email: String
  firstname: String
  lastname: String
  role: UserType
  gender: Gender
}

enum Gender {
  FEMALE
  MALE
}

enum UserType {
  PRINCIPLE
  TEACHER
  STUDENT
}
