input InputUser {
    username: String!
    email: String
    firstname: String
    lastname: String
    gender: Gender
    role: UserType
}

input InputStudent {
    username: String!
    email: String
    firstname: String
    lastname: String
    gender: Gender
    class: Class
}

input InputClass {
    name: String!
    level: String!
    number: Int!
}

type Mutation {
    createUser(user: InputUser!) : User
    updateUser(id: ID!, user: InputUser!) : User
    deleteUser(id: ID!) : Int

    createStudent(user: InputStudent!) : Student
    updateStudent(id: ID!, student: InputStudent!) : Student
    deleteStudent(id: ID!) : Int

    createClass(class: InputClass!): Class
    updateClass(id: ID!, class: InputClass!): Class
    deleteClass(id: ID!): Int
}