input InputUser {
    username: String!
    email: String
    firstname: String
    lastname: String
    role: UserType
}

input InputClass {
    name: String!
    level: String!
    number: Int!
}

type Mutation {
    addUser(user:InputUser!) : User
    updateUser(id: ID!, user:InputUser!) : User
    deleteUser(id: ID!) : Int

    createClass(class: InputClass!): Class
    updateClass(id: ID!, class: InputClass!): Class
    deleteClass(id: ID!): Int
}