#!/bin/bash

CUR_VER=$(./scripts/echo-version package.json)

if [ "$BRANCH" == 'master' ] || [ "$BRANCH" == 'new-k8s-deployment' ]
then
    echo info::deploy:: branch is ${BRANCH}, deploying new version [${CUR_VER}] to k8s
    # update image
    kubectl set image deployment/msw-server-deployment msw-server=myspecialway/msw-server:${CUR_VER}
else
    echo info::deploy:: branch is not master, skipping deployment
fi