#!/bin/bash

if [$BRANCH == 'master']
then
    docker push myspecialway/msw-server:$(./scripts/echo-version package.json)
    docker push myspecialway/msw-server:latest
else
    docker push myspecialway/msw-server:$BRANCH
fi  