#!/bin/bash

docker pull node:carbon
if [ "$BRANCH" = 'master' ]
then
   echo info::docker:: build is on \"master\" branch incrementing version and building
   yarn version --new-version patch
   docker build . -t myspecialway/msw-server:$(./scripts/echo-version package.json) -t myspecialway/msw-server:latest
elif [ "$TRAVIS_PULL_REQUEST" == "true" ]
then
    echo branch is a pull request, skipping docker 
else
    echo branch $BRANCH is not master, building without version increment
    echo myspecialway/msw-server:$(echo $BRANCH | sed 's/\///g')
   docker build . -t myspecialway/msw-server:$(echo $BRANCH | sed 's/\///g')
fi