#!/bin/bash

jest --coverage && codecov || exit 1
rm -rf coverage

npx jest --rootDir=. --testRegex=.e2e-spec.ts$ --maxWorkers=4 --coverage --coverageReporters=lcov --coverageDirectory=coverage && codecov || exit 1
rm -rf coverage

