#!/bin/bash

npx jest --coverage && npx codecov || exit 1
rm -rf coverage

# echo "TODO:: BAD CODE:: removed e2e tests to not break coverage created separate task to me them work"
npx jest --config ./jest-e2e.json --coverage && npx codecov || exit 1
rm -rf coverage

